model:
  # arch: baseline18_single
  arch: baseline18_double
  # arch: baseline34_single_decoder1
  # arch: baseline34_single_decoder2
  # arch: baseline34_double
  # arch: baseline34
  # arch: ACNet
  # arch: CANet
  # arch: CMANet
  # arch: CMGFNet
  # arch: CMGFNet_U
  # arch: DE_CCFNet_18
  # arch: DE_CCFNet_34
  # arch: CMFNet      # 这个不能用
  # arch: DE_DCGCN
  # arch: HAFNetE
  # arch: PACSCNet    # 这个不能用
  # arch: PCGNet
  # arch: SFAFMA50
  # arch: SFAFMA101
  
data:
  path: /home/icclab/Documents/lqw/DatasetMMF/OSTD
  train_split: train
  val_split: val
  test_split: test
  # img_size: 512
  img_size: 128
  bands1: 193
  bands2: 3
  classes: 1
  classification: Binary
  # classification: Multi

training:
  train_epoch: 10
  batch_size: 32
  test_batch_size: 1
  # n_workers: 4
  n_workers: 6
  optimizer:
    name: 'adam'
    lr: 0.001
#    weight_decay: 0.0005
#    momentum: 0.95
#  gaofen_optimizer:
#    name: 'adam'
#    lr: 0.001
  loss:
    # name: 'dice_loss'
    # name: 'focal_bce_loss'
    name: 'dice_bce_loss_re'
    # name: 'gaploss'
    # name: 'multi_loss'
    # name: 'multi_loss2'
    # name: 'multi_loss3'

    size_average: True
    device: 0
    a: 1
    b: 1
#    c: 1
#    weight: [0.93, 1.07]

  lr_schedule:
    name: ReduceLROnPlateau

results:
  path: /home/icclab/Documents/lqw/Multimodal_Segmentation/TilewiseSegFra/run

threshold: 0.5






