model:
  # arch: baseline18
  arch: baseline34
  # arch: ACNet
  # arch: CANet
  # arch: CMANet
  # arch: CMGFNet
  # arch: CMGFNet_U
  # arch: DE_CCFNet_18
  # arch: DE_CCFNet_34
  # arch: CMFNet      # 这个不能用
  # arch: DE_DCGCN
  # arch: HAFNetE
  # arch: PACSCNet    # 这个不能用
  # arch: PCGNet
  # arch: SFAFMA50
  # arch: SFAFMA101

data:
  # path: C:\Users\jc962911\Project\Semantic_Segmentation\multiRoad\multi_data
  path: /home/leo/MMF/OSDT
  train_split: train2
  val_split: val2
  test_split: test2
  # img_size: 512
  img_size: 128

training:
  train_epoch: 100
  # batch_size: 4
  batch_size: 32
  test_batch_size: 1
  # n_workers: 4
  n_workers: 6
  optimizer:
    name: 'adam'
    lr: 0.001
#    weight_decay: 0.0005
#    momentum: 0.95
#  gaofen_optimizer:
#    name: 'adam'
#    lr: 0.001
  loss:
    # name: 'dice_loss'
    # name: 'focal_bce_loss'
    name: 'dice_bce_loss_re'
    # name: 'gaploss'
    # name: 'multi_loss'
    # name: 'multi_loss2'
    # name: 'multi_loss3'

    size_average: True
    device: 0
    a: 1
    b: 1
#    c: 1
#    weight: [0.93, 1.07]

  lr_schedule:
    name: ReduceLROnPlateau

threshold: 0.5






