model:
  # arch: baseline18_single
  # arch: baseline18_double
  # arch: baseline34_single_decoder1
  # arch: baseline34_single_decoder2
  # arch: baseline34_double
  # arch: baseline34
  # arch: AsymFormer_b0
  # arch: ACNet
  # arch: CANet50
  # arch: CMANet
  # arch: CMGFNet18
  arch: CMGFNet34
  # arch: DE_CCFNet18
  # arch: DE_CCFNet34
  # arch: DE_CCFNet34_3B
  # arch: CMFNet
  # arch: DE_DCGCN
  # arch: FAFNet50
  # arch: FAFNet101
  # arch: MGFNet_Wei50
  # arch: MGFNet_Wu34
  # arch: HAFNetE
  # arch: PACSCNet50
  # arch: PACSCNet101
  # arch: PCGNet18
  # arch: PCGNet34
  # arch: SOLC
  # arch: SFAFMA50
  # arch: SFAFMA101

data:
  # name: OSTD
  # path: /home/icclab/Documents/lqw/DatasetMMF/OSTD
  # train_split: train
  # val_split: val
  # test_split: test
  # img_size: 128
  # bands1: 193
  # bands2: 3
  # classes: 1
  # batch_size: 32
  # ignore_index: 999
  # classification: Binary
  # modality: rgb
  # # modality: lidar
  # # modality: sar

  name: Vaihingen
  path: /home/icclab/Documents/lqw/DatasetMMF/Vaihingen
  train_split: train
  val_split: val
  test_split: test
  img_size: [256, 256]
  bands1: 3
  bands2: 1
  classes: 6
  train_epoch: 100
  batch_size: 32
  ignore_index: 5
  normalization: standard # zScore, standard, minMax
  classification: Multi
  modality: rgb
  # modality: lidar
  # modality: sar
  
  # name: Potsdam
  # path: /home/icclab/Documents/lqw/DatasetMMF/Potsdam
  # train_split: train
  # val_split: val
  # test_split: test
  # img_size: [512, 512]
  # bands1: 3
  # bands2: 1
  # classes: 6
  # train_epoch: 100
  # batch_size: 12
  # ignore_index: 5
  # normalization: standard # zScore, standard, minMax
  # classification: Multi
  # modality: rgb
  # # modality: lidar
  # # modality: sar

  # name: ISA
  # path: /home/icclab/Documents/lqw/DatasetMMF/ISASeg
  # # path: /home/icclab/Documents/lqw/DatasetMMF/ISASeg_train
  # train_split: train
  # val_split: val
  # test_split: test
  # # img_size: 1536
  # img_size: 256
  # bands1: 3
  # bands2: 12
  # classes: 1
  # train_epoch: 100
  # batch_size: 2
  # ignore_index: 1
  # classification: Binary
  # modality: rgb
  # # modality: lidar
  # # modality: sar

training:
  GPUS: [0, 1]
  find_unused_parameters: True
  test_batch_size: 1
  n_workers: 4
  optimizer:
    name: 'adam'
    lr: 0.004
  scheduler:
    factor: 0.6
    patience: 7
#    weight_decay: 0.0005
#    momentum: 0.95
#  gaofen_optimizer:
#    name: 'adam'
#    lr: 0.001
  loss:
    # name: 'dice_bce_loss_re'

    name: 'multiclass_multi_loss'
    classes: 6
    a: 1
    b: 1

    # name: 'dice_loss'
    # name: 'focal_bce_loss'
    # name: 'gaploss'
    # name: 'multi_loss'
    # name: 'multi_loss2'
    # name: 'multi_loss3'

#    c: 1
#    weight: [0.93, 1.07]

  lr_schedule:
    name: ReduceLROnPlateau

threshold: 0.5



